name: Update Docs

on:
  push:
    branches: [ master ]

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install .
    - name: Build docs
      run: |
        cd docs-src
        make